[package]
name = "telegram_drive_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "telegram_drive_core"
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"

[dependencies]
serde_json = "1.0.95"
tokio = { version = "1.27.0", features = ["full"] }
futures = "0.3.28"